name: Github Workflow

on:
  push:
    branches: [ master, feature/** ]

  pull_request:
    branches: [ master, feature/** ]

jobs:
  chore:
      runs-on: ubuntu-latest
      steps:
          - name: 'Run Pre-commit'
            run: |
                yarn
                yarn lint-staged
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        yarn
#        npx webpack
